version: '3.4'

services:
  
  sqwads.api:
    environment:
      - ConnectionStrings__SqwadsDb=Server=sqwads.db;Database=Sqwads;User Id=sa;Password=Pass@word;Encrypt=False
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5003:80"
  
  sqwads.db:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - sqwads-sqldata:/var/opt/mssql
   